"""Builds the deployable files from src/. Run after changing anything in src/:

    python3 tools/bundle.py

Outputs
  dist/Code.gs, dist/Index.html, dist/appsscript.json
      Paste-ready Apps Script project (backend + optional Google-hosted app).
  index.html  (repository root)
      The GitHub Pages app. Loads config.js for the Apps Script URL.
  config.js   (repository root, created once, never overwritten)
      Holds CL_API_URL — edit it after deploying the Apps Script web app.
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'src')
DIST = os.path.join(ROOT, 'dist')
GS_ORDER = ['Code', 'Api', 'Utils', 'Database', 'Config', 'Audit', 'Users', 'Commission', 'Time', 'Activity',
            'Schedules', 'Sales', 'Packages', 'Reports', 'Setup', 'Tests']


def read(name):
    with open(os.path.join(SRC, name), encoding='utf-8') as f:
        return f.read()


def write(path, text):
    with open(path, 'w', encoding='utf-8') as f:
        f.write(text)


def page():
    html = read('Index.html')
    html = re.sub(r"<\?!=\s*include_\('CSS'\);?\s*\?>", lambda m: read('CSS.html'), html)
    html = re.sub(r"<\?!=\s*include_\('JS'\);?\s*\?>", lambda m: read('JS.html'), html)
    assert '<?' not in html, 'template tag left in bundle'
    return html


def main():
    os.makedirs(DIST, exist_ok=True)
    missing = [n for n in os.listdir(SRC) if n.endswith('.gs') and n[:-3] not in GS_ORDER]
    assert not missing, 'add to GS_ORDER: ' + ', '.join(missing)
    gs = '\n\n'.join('// ===== ' + n + '.gs =====\n' + read(n + '.gs') for n in GS_ORDER)
    write(os.path.join(DIST, 'Code.gs'),
          '// ClickLounge Sales Dashboard — bundled from src/ by tools/bundle.py. Edit src/, not this file.\n\n' + gs)
    html = page()
    write(os.path.join(DIST, 'Index.html'), html)
    write(os.path.join(DIST, 'appsscript.json'), read('appsscript.json'))

    banner = '<!-- Generated by tools/bundle.py from src/ — edit src/, not this file. -->\n'
    pages = banner + html.replace('</title>', '</title>\n  <script src="config.js"></script>', 1)
    write(os.path.join(ROOT, 'index.html'), pages)
    cfg = os.path.join(ROOT, 'config.js')
    if not os.path.exists(cfg):
        write(cfg, "// Paste your Apps Script web app URL (ends in /exec) between the quotes.\n"
                   "window.CL_API_URL = '';\n")
    write(os.path.join(ROOT, '.nojekyll'), '')
    print('Built dist/Code.gs, dist/Index.html, dist/appsscript.json, index.html')


if __name__ == '__main__':
    main()
